// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UsedGoodsTracker.Data;

#nullable disable

namespace UsedGoodsTracker.Data.Migrations
{
    [DbContext(typeof(UsedGoodsTrackerDbContext))]
    partial class UsedGoodsTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UsedGoodsTracker.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EbayCategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchKeywords")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EbayCategoryId")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("UsedGoodsTracker.Core.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("EbayEpid")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("UsedGoodsTracker.Core.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DaysToSell")
                        .HasColumnType("integer");

                    b.Property<string>("EbayItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfirmedSold")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNoLongerActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemWebUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ListedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationCity")
                        .HasColumnType("text");

                    b.Property<string>("LocationCountry")
                        .HasColumnType("text");

                    b.Property<string>("LocationPostalCode")
                        .HasColumnType("text");

                    b.Property<string>("LocationStateOrProvince")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<int?>("SellerFeedbackScore")
                        .HasColumnType("integer");

                    b.Property<string>("SellerUsername")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SoldPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EbayItemId")
                        .IsUnique();

                    b.HasIndex("ItemId");

                    b.HasIndex("LocationStateOrProvince");

                    b.HasIndex("CategoryId", "Condition");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("UsedGoodsTracker.Core.Models.PriceObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ListingId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "ObservedAt");

                    b.ToTable("PriceObservations");
                });

            modelBuilder.Entity("UsedGoodsTracker.Core.Models.Item", b =>
                {
                    b.HasOne("UsedGoodsTracker.Core.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UsedGoodsTracker.Core.Models.Listing", b =>
                {
                    b.HasOne("UsedGoodsTracker.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UsedGoodsTracker.Core.Models.Item", "Item")
                        .WithMany("Listings")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("UsedGoodsTracker.Core.Models.PriceObservation", b =>
                {
                    b.HasOne("UsedGoodsTracker.Core.Models.Listing", "Listing")
                        .WithMany("PriceObservations")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("UsedGoodsTracker.Core.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("UsedGoodsTracker.Core.Models.Item", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("UsedGoodsTracker.Core.Models.Listing", b =>
                {
                    b.Navigation("PriceObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
