<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-UsedGoodsTracker.Ingestion-1dd9bf91-0856-406e-9a27-3bd289f15490</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Quartz" Version="3.13.1" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.13.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UsedGoodsTracker.Core\UsedGoodsTracker.Core.csproj" />
    <ProjectReference Include="..\UsedGoodsTracker.Data\UsedGoodsTracker.Data.csproj" />
  </ItemGroup>
</Project>
