<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\UsedGoodsTracker.Core\UsedGoodsTracker.Core.csproj" />
    <ProjectReference Include="..\UsedGoodsTracker.Data\UsedGoodsTracker.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Radzen.Blazor" Version="11.1.6" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
